source 'https://rubygems.org'

gem "bundler", "~> 1.3"
gem 'rspec'
gem 'guard'
gem 'guard-rspec'
gem 'nokogiri'
gem 'sequel'
gem 'diffy'
gem 'sqlite3'
gem 'twitter'
gem 'zip'
gem 'parallel'
gem 'ronn'
